# Generated by Django 6.0.1 on 2026-01-19 04:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projectVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='projects/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'MACHINE LEARNING'), ('AI', 'ARTIFICIAL INTELLIGENCE'), ('WD', 'WEB DEVELOPMENT'), ('SEIR', 'SEARCH ENGINE INFO RETRIEVAL')], max_length=4)),
            ],
        ),
    ]
